_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -81.9141
  - 43.9928
  - 5
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: ''
source: "mbtiles:///tiles/firecares_addresses.mbtiles"
styles: 
  - style.mss
template: ''
